### ISSUE TITLE
Email address from iCloud is not displayed after restore

### ISSUE THREAD

**Issue by tanx** [photon-sdk/photon-lib#15]
I was testing this morning (Xs, 13.4.1) by deleting and reinstalling the app. 
 - I set a pin and registered my email address on the first install
 - Transferred some sats
 - Deleted app
 - Reinstalled from testflight
 - Wallet balance was restored, but I noticed my email wasn't displayed under Settings
 - When I tried to reset it to the same, I got a msg saying the user ID was already in use.

**Comment by pitoi** [comment]
Once I reset my email, the forgot PIN process worked well. The PIN restore process could not be repeated for 1 month, which was surprising to me. If the restore email is assumed to be trusted, than why limit the frequency? Separately, I did expect the PIN to have a restriction on the number of attempts, but it seems unlimited.

**Comment by tanx** [comment]
> If the restore email is assumed to be trusted, than why limit the frequency?

This is a safety measure to mitigate a SIM swap attach e.g. in case the user sets the same email address as their iCloud account. More info here:
https://github.com/photon-sdk/photon-lib/blob/master/threat-model.md#forgotten-pin

> Separately, I did expect the PIN to have a restriction on the number of attempts, but it seems unlimited.

Local wallet unlock is not rate limited. Key server authentication is:
https://github.com/photon-sdk/photon-lib/blob/master/threat-model.md#pin-brute-force-attack

**Comment by tanx** [comment]
I pushed update `0.1.1` to testflight which should resolve the issue. It's still in app store review but should got out within the next day or so. Let me know if you still experience the issue.

**Comment by tanx** [comment]
Going to mark this as closed for now as I could not reproduce the issue in `0.1.1`. Let me know if you experience this issue again.
